<?php ob_start(); ?>

    <div class="mx-auto mt-5 w-25 border border-2 border-dark bg-info p-5 rounded-3">
        <h2 class="text-uppercase text-center text-info fs-1 fw-bold fst-italic bg-dark"  >Inscription</h2>

        <form  method="post" >
            
            <div class="form-group">
                <label for="" class="fs-2 fw-bold fst-italic">Prénom:</label>
                <input type="text" name="prenom" class="form-control">
            </div>
            <div class="form-group">
                <label for="" class="fs-2 fw-bold fst-italic">Nom:</label>
                <input type="text" name="nom" class="form-control">
            </div>
            <div class="form-group">
                <label for="" class="fs-2 fw-bold fst-italic">Login:</label>
                <input type="text" name="login" class="form-control">
            </div>
            <div class="form-group">
                <label for="" class="fs-2 fw-bold fst-italic text-capitalize">Mot de passe:</label>
                <input type="password" name="mdp" class="form-control">
            </div>

            <br>
        
                <input type="submit" class="btn btn-primary fw-bold fs-2 fst-italic">
        </form>    
    </div>


<?php $content = ob_get_clean();

    include "vues/template.phtml";