<?php ob_start(); ?>

    <div class="container card mx-auto d-block text-white bg-dark my-5" style="width: 30%;">
        <h2 class="text-center text-info text-uppercase fs-1 fst-italic fw-bold">Inscription</h2>

        <form  method="post" >
            
            <div class="form-group">
                <label for="" class="fs-2 fw-bold fst-italic">Prénom:</label>
                <input type="text" name="prenom" class="form-control">
            </div>
            <div class="form-group">
                <label for="" class="fs-2 fw-bold fst-italic">Nom:</label>
                <input type="text" name="nom" class="form-control">
            </div>
            <div class="form-group">
                <label for="" class="fs-2 fw-bold fst-italic">Login:</label>
                <input type="text" name="login" class="form-control">
            </div>
            <div class="form-group">
                <label for="" class="fs-2 fw-bold fst-italic text-capitalize">Mot de passe:</label>
                <input type="password" name="mdp" class="form-control">
            </div>

            <br>
        
                <input type="submit" class="btn btn-outline-secondary mb-3">
        </form>    
    </div>


<?php $content = ob_get_clean();

    include "vues/template.phtml";
