<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/bootstrap.min.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>MyBlog</title>
    
</head>
<body>
    
    <header class="text-white  topnav">
      

<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-5 border border-0 border-bottom border-info border-5 mb-2">
        <div class="container-fluid">
            <h1 class="text-secondary text-uppercase  fs-1 fst-italic ">
                <a href="."><i class="fas fa-microphone"></i>Encore un blog</a> 
            </h1>
           
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

            
        <div class="d-flex">
                
            <?php/*if (!empty($_SESSION['auteur'])) : */?>
                <nav class="btn btn-outline-secondary text-decoration-none  text-uppercase">
                    <a href="?action=adminArt" class="text-decoration-none"><i class="fas fa-cogs"></i> Administration</a>
                </nav>
            <?php/* endif; */?> 
            &nbsp;  &nbsp;
            <nav>
                <?php if (empty($_SESSION['auteur'])): ?>
                    <a href="?action=inscription" class="btn btn-outline-secondary  text-uppercase" >Inscription</a> 
                    &nbsp;  &nbsp;
                    <a href="?action=connexion" class="btn btn-outline-secondary  text-uppercase" >Connexion</a>
                <?php else: ?>
                    <div class="text-end ">
                        <?= "Bonjour " . unserialize($_SESSION['auteur'])->getPrenom() ?>
                        <a href="?action=deconnexion" class="btn btn-outline-danger text-decoration-none text-uppercase ">Déconnexion</a>
                    </div>
                <?php endif; ?>
                </div>
           
        </div>
</nav>

        
    </header>

    <main class="container-fluid  mb-5">
        <?= $content?? "contenu vide" ?>
    </main>

    <footer class="py-5 bg-dark border-top border-info border-5 mb-0 mt-3">
        <div class="container">
            <p class="m-0 text-center text-uppercase text-white fs-1 fw-bold fst-italic"> &copy; 2020 - 2021 / Blog - M-Wone <?= date("d/m/Y") ?></p>
        </div>
    </footer>
</body>
</html>