<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>MyBlog</title>
    <style>
        .topnav a:hover {
                            background-color: #ddd;
                            color: black;
                        }

 
    </style>
</head>
<body>
    
    <header class="bg-dark p-5 text-white border border-0 border-bottom border-info border-5 mb-2 topnav">
        <h1 class="text-center text-uppercase text-primary fs-1 fst-italic fw-bold">
            <a href="."><i class="fas fa-microphone"></i>Encore un blog</a> 
        </h1>

        <nav class="text-end fs-1 fst-italic fw-bold">
            <a href="?action=adminArt"><i class="fas fa-cogs"></i> Administration</a>
        </nav>

        <nav>
            <?php if( empty($_SESSION['auteur'])): ?>
                <a href="?action=inscription" class="fs-1 fst-italic fw-bold text-decoration-none mark">Inscription</a>
                &nbsp;  &nbsp;
                <a href="?action=connexion" class="fs-1 fst-italic fw-bold text-decoration-none mark">Connexion</a>
            <?php else: ?>
                <div class="text-end fs-1 fst-italic fw-bold">
                    <?= "Bonjour " . unserialize($_SESSION['auteur'])->getPrenom() ?>
                    <a href="?action=deconnexion" class="text-decoration-none"><mark>Déconnexion</mark></a>
                </div>
            <?php endif; ?>    
        </nav>

        
    </header>

    <main class="container-fluid  mb-5">
        <?= $content?? "contenu vide" ?>
    </main>

    <footer class="py-5 bg-dark border-top border-info border-5  mt-3">
        <div class="container">
            <p class="m-0 text-center text-uppercase text-white fs-1 fw-bold fst-italic"> &copy; 2020 - 2021 / Blog - M-Wone <?= date("d/m/Y") ?></p>
        </div>
    </footer>
</body>
</html>